### ISSUE TITLE
Macbok pro 14,3  working touchbar (off-topic issue raised in reply to a discussion elsewhere)

### ISSUE THREAD

**Issue by davidjo** [therainydev/lizhi#2]
Sorry but this seems to be the only way on github to msg you to see if you saw my comments after you closed the issue and mentioned touchbar not working - I thought you might get notified about my comment addition but maybe not.

I have had the touchbar working for  years - and I have it working now - but there was an issue around Ubuntu 20.04 upgrade which stopped it working - the issue has still not been fixed - this is the usbmuxd udev file problem in my comment.

**Comment by therainydev** [comment]
Yes, I was notified. Thank you anyways, though.

I would prefer it if you had emailed me via my Git commit email address instead.
